language: node_js

node_js:
  - 0.8
services:
  - couchdb

env:
  global:
    - secure: "M0xltS2tLEYNJypb5LV0ZcJo1G3LEDn002mUCA1yg9mHcvxVUDuuf1WRGWdv\n4GK8LJH5xB6DiVFLj2Gz2jTzBJM8zk2mTy0PL0hDpLVgF2wxUgObBg08XzSv\n3CqGfDUU612EEaezFKmf9nQ5bGH1LJrsAJDv6hK1T45Lyo4tPoY="
    - secure: "fL+1vGzXKNd85tUHf8VhWijaPoYXsxK/xqjoFPi0c75VFH/BLxBSn7gStCqG\nX2/eJnRXPfGKonlUZSmusbZj41f7ZEKpdqltY0i9M7KBhfDTCjpXi7Pnd0hY\n5IkNcjd7T/H6aspLGaDzNq7TxgNrInlqdFn5lWB8CF2XFZWgm9s="
    - WTF=testing