language: node_js

node_js:
  - 0.8
services:
  - couchdb

env:
  global:
    - secure: "YCwG0LtgaJf9PiqSZy9J7OWr74IjiJtL7ctkQp6P6nC3YBd3gK7FxZFMO5r4\nym3pggzCGGTxk6mAX4uTz/aorKYQcfjaDSeycZzD9QHSVAAC5uwVlg4vjdRW\ndUYaHrrcCzwJ/bC+NqXKRuzUiyRLxKOkTM63/sQ5Z0ws8ceiKE4="
    - WTF=testing