language: node_js

node_js:
  - 0.8
services:
  - couchdb

env:
  global:
    - secure: "SQP3/PirhzPuiJBy9t8YvhfLrtwIXB86VyUYHHCeJ0bnlU8C1GbeBIg7QFA5\nMMqfWpgh2FoDzR5LU8zryIW8qRNnsdES2CiU11U6xFkN7oBXUMGIqwn9/CvP\nbN+LIkILztIuK+wuJ+9dkrImu+wmiadiMb6JfBQmO9pEMBDhaVk="
    - WTF=testing