language: node_js

node_js:
  - 0.8
services:
  - couchdb

env:
  global:
    - secure: "hm7ffVjSyMp6slHKeTuMSnsoglKeaOC5MBp+HDidXCc6Xe6Pz6eslxxETx1x\nATDYhWlH30yBTI5ND1mZL4wh6Cy+/5v6GgfuHYQvX08GoDaR+88kzGutDbbu\nY1SH8xFvQDj38xMjyYBkCp/YcNgI1/OMgAj9NJLEAsSlrl0duoc="
    - secure: "fL+1vGzXKNd85tUHf8VhWijaPoYXsxK/xqjoFPi0c75VFH/BLxBSn7gStCqG\nX2/eJnRXPfGKonlUZSmusbZj41f7ZEKpdqltY0i9M7KBhfDTCjpXi7Pnd0hY\n5IkNcjd7T/H6aspLGaDzNq7TxgNrInlqdFn5lWB8CF2XFZWgm9s="
    - WTF=testing