language: node_js

node_js:
  - 0.8
services:
  - couchdb

env:
  global:
    - secure: "pomm3YGv8+FNbuNf+EmHvAvYbuEzq86r9JGNgsSGCX57Z4PhL8gkBeeRODHs\nkDzJeocyeEUghaE7SczOKnQ+Uy9oYF5FAk0PMTWxhj31t0DLwzVlu/YwZWwb\nTPknoGpjiJs/ELJ2se4vTqL2gMp2fs942pvpw4ijiRZ93tHkNhU="