language: node_js

node_js:
  - 0.8
services:
  - couchdb

env:
  global:
    - secure: "OnoZ8HWs3FGbQxUE6UBtfnEsu8qF7dciv4Vx0B99nmFUXe5BUHE4836Tm5bH\nQaeef14aiJ/WJXSNzBj5aIwlLgc+Oyok776YkoYGWdThc5Xp6ZqRrpVSiISM\nHASBoQOICYd6NlZKGGFBptWkHDM0JXsgfF1zBWT2vsz6nL4782E="
    - secure: "fL+1vGzXKNd85tUHf8VhWijaPoYXsxK/xqjoFPi0c75VFH/BLxBSn7gStCqG\nX2/eJnRXPfGKonlUZSmusbZj41f7ZEKpdqltY0i9M7KBhfDTCjpXi7Pnd0hY\n5IkNcjd7T/H6aspLGaDzNq7TxgNrInlqdFn5lWB8CF2XFZWgm9s="
    - WTF=testing