language: node_js

node_js:
  - 0.8
services:
  - couchdb

env:
  global:
    - secure: "oFxOiqJlOOuDn7SYxvfkMdt96mcow5uRr69mXTsSHMlPEd9TRQkMg9b1qrbW\nx7pnJ/vNCr1LYKH5EBxwYoDrWa9uqb1lmnzystEO9PRVoDONGvD5XUa93J9n\nn28/Gg1rFHk1C8gVTC8SKv4S2b6oFgAVrIG3sFqfFAtlpBJu27s="